version: "3"
services:
  server:
    image: index.docker.io/cloudtogouser/pageplug-ce:v1.9.37
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "${APP_PORT_HTTP}:80"
      - "${APP_PORT_HTTPS}:443"
    volumes:
      - "${DATA_PATH}:/appsmith-stacks"
    env_file:
      - .env
    labels:
      createdBy: "Apps"
    ## Uncomment the lines below to enable auto-update
      com.centurylinklabs.watchtower.enable: "true"

  auto_update:
    image: containrrr/watchtower:latest-dev
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    ## Update check interval in seconds.
    command: --schedule "0 0 * ? * *" --label-enable --cleanup
    restart: unless-stopped
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true