version: "3"
services:
  server:
    image: registry.cn-hangzhou.aliyuncs.com/mindoc-org/mindoc:v2.1
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    privileged: false
    networks:
      - 1panel-network
    environment:
      - "TZ=Asia/Shanghai"
      - MINDOC_RUN_MODE=prod
      - MINDOC_DB_ADAPTER=mysql
      - MYSQL_PORT_3306_TCP_ADDR=${DB_HOST}
      - MYSQL_PORT_3306_TCP_PORT=${DB_PORT}
      - MYSQL_INSTANCE_NAME=#{DB_NAME}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MINDOC_CACHE=false
      - MINDOC_ENABLE_EXPORT=false
    ports:
      - "${APP_PORT_HTTP}:8081"
    volumes:
      - ${DATA_DIR}/mindoc/conf:/mindoc/conf
      - ${DATA_DIR}/mindoc/static:/mindoc/static
      - ${DATA_DIR}/mindoc/views:/mindoc/views
      - ${DATA_DIR}/mindoc/uploads:/mindoc/uploads
      - ${DATA_DIR}/mindoc/runtime:/mindoc/runtime
      - ${DATA_DIR}/mindoc/database:/mindoc/database
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true