version: '3'
services:
  immich-server:
    container_name: ${CONTAINER_NAME}-server
    restart: always
    networks:
      - 1panel-network
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - config.env
    environment:
      IMMICH_WORKERS_INCLUDE: 'api'
    ports:
      # 2283 (server), 3003 (machine learning) 8081(IMMICH_API_METRICS_PORT) 8082(IMMICH_MICROSERVICES_METRICS_PORT)
      - ${PANEL_APP_PORT_HTTP}:2283
    # depends_on:
    #   - immich-redis
    #   - immich-database
    labels:  
      createdBy: "Apps"

  immich-microservices:
    container_name: ${CONTAINER_NAME}-microservices
    restart: always
    networks:
      - 1panel-network
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - config.env
    environment:
      IMMICH_WORKERS_EXCLUDE: 'api'
    # depends_on:
    #   - immich-redis
    #   - immich-database
    labels:  
      createdBy: "Apps"

  immich-machine-learning:
    container_name: ${CONTAINER_NAME}-machine_learning
    restart: always
    networks:
      - 1panel-network
    image: altran1502/immich-machine-learning:release
    volumes:
      - ${CACHE_PATH}:/cache
    env_file:
      - config.env
    labels:  
      createdBy: "Apps"

  # immich-redis:
  #   container_name: immich_redis
  #   restart: always
  #   networks:
  #     - 1panel-network
  #   image: "redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5"
  #   labels:  
  #     createdBy: "Apps"

  immich-database:
    container_name: immich_postgres
    restart: always
    networks:
      - 1panel-network
    image: "tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0"
    env_file:
      - config.env
    environment:
      - POSTGRES_PASSWORD=${PANEL_DB_USER_PASSWORD}
      - POSTGRES_USER=${PANEL_DB_USER}
      - POSTGRES_DB=${PANEL_DB_NAME}
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true