version: "3"

networks:
  1panel-network:
    external: true

services:
  gitea:
    image: gitea.cn/gitea/gitea:1.21.7
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    environment:
      - USER=${PANEL_APP_USER}
      - USER_UID=${PANEL_APP_USER_UID}
      - USER_GID=${PANEL_APP_USER_GID}
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__SSH_LISTEN_PORT=22
      - GITEA__server__SSH_PORT=${PANEL_APP_PORT_SSH}
      - GITEA__database__DB_TYPE=${PANEL_DB_TYPE}
      - GITEA__database__HOST=${PANEL_DB_HOST}:${PANEL_DB_PORT}
      - GITEA__database__NAME=${PANEL_DB_NAME}
      - GITEA__database__USER=${PANEL_DB_USER}
      - GITEA__database__PASSWD=${PANEL_DB_USER_PASSWORD}
    env_file:
      - .env
    volumes:
      - ${GITEA_ROOT_PATH}/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
      - "${PANEL_APP_PORT_SSH}:22"
