version: "3"
services:
  server:
    image: registry.cn-hangzhou.aliyuncs.com/zmister/mrdoc:v8
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - 1panel-network
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - "${PANEL_APP_PORT_HTTP}:10086"
    volumes:
      - "${DATA_PATH}:/app/MrDoc"
      - "${CONFIG_PATH}:/app/config.ini"
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true