version: "2"

networks:
  1panel-network:
    external: true

services:
  nacos:
    image: nacos/nacos-server:${RELEASE_VERSION}
    container_name: ${CONTAINER_NAME}
    restart: always
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network
    environment:
      - PREFER_HOST_MODE=ip
      - MODE=standalone
      - JVM_XMS=${JVM_XMS}
      - JVM_XMX=${JVM_XMX}
      - JVM_XMN=${JVM_XMN}
      - JVM_MS=${JVM_MS}
      - JVM_MMS=${JVM_MMS}
      - NACOS_AUTH_IDENTITY_KEY=${NACOS_AUTH_IDENTITY_KEY}
      - NACOS_AUTH_IDENTITY_VALUE=${NACOS_AUTH_IDENTITY_VALUE}
      - NACOS_AUTH_TOKEN=${NACOS_AUTH_TOKEN}
      - NACOS_SERVER_IP=${NACOS_SERVER_IP}
      - SPRING_DATASOURCE_PLATFORM=${SPRING_DATASOURCE_PLATFORM}
      - MYSQL_SERVICE_HOST=${MYSQL_SERVICE_HOST}
      - MYSQL_SERVICE_PORT=${MYSQL_SERVICE_PORT}
      - MYSQL_SERVICE_USER=${MYSQL_SERVICE_USER}
      - MYSQL_SERVICE_PASSWORD=${MYSQL_SERVICE_PASSWORD}
      - MYSQL_SERVICE_DB_NAME=${MYSQL_SERVICE_DB_NAME}
      - MYSQL_SERVICE_DB_PARAM=${MYSQL_SERVICE_DB_PARAM}
    volumes:
      - ${NACOS_DATA_ROOT_PATH}/logs:/home/nacos/logs
      - ${NACOS_DATA_ROOT_PATH}/data:/home/nacos/data
    ports:
      - ${PANEL_APP_PORT_HTTP}:8848
      - ${NACOS_COMMUNICATION_PORT}:9848
