version: "3"

networks:
  1panel-network:
    external: true

services:
  jumpserver:
    image: jumpserver/jms_all:v3.10.6
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    privileged: true
    environment:
      SECRET_KEY: ${SECRET_KEY}
      BOOTSTRAP_TOKEN: ${BOOTSTRAP_TOKEN}
      DEBUG: ${DEBUG:-FALSE}
      LOG_LEVEL: ${LOG_LEVEL}
      DB_HOST: ${PANEL_DB_HOST}
      DB_PORT: ${PANEL_DB_PORT}
      DB_USER: ${PANEL_DB_USER}
      DB_PASSWORD: ${PANEL_DB_USER_PASSWORD}
      DB_NAME: ${PANEL_DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${PANEL_REDIS_ROOT_PASSWORD}
      MAGNUS_MYSQL_PORT: ${MAGNUS_MYSQL_PORT}
      MAGNUS_MARIADB_PORT: ${MAGNUS_MARIADB_PORT}
      MAGNUS_POSTGRESQL_PORT: ${MAGNUS_POSTGRESQL_PORT}
      MAGNUS_REDIS_PORT: ${MAGNUS_REDIS_PORT}
      DOMAINS: ${DOMAINS:-}
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
      - ${RDP_PORT}:3389
      - ${SSH_PORT}:2222
      - ${MAGNUS_MYSQL_PORT}:33061
      - ${MAGNUS_MARIADB_PORT}:33062
      - ${MAGNUS_POSTGRESQL_PORT}:54320
      - ${MAGNUS_REDIS_PORT}:63790
    volumes:
      - ${JUMPSERVER_ROOT_PATH}/data/core/data:/opt/jumpserver/core/data
      - ${JUMPSERVER_ROOT_PATH}/data/koko/data:/opt/jumpserver/koko/data
      - ${JUMPSERVER_ROOT_PATH}/data/lion/data:/opt/jumpserver/lion/data
      - ${JUMPSERVER_ROOT_PATH}/data/magnus/data:/opt/jumpserver/magnus/data
      - ${JUMPSERVER_ROOT_PATH}/data/nginx/data:/var/log/nginx
