version: "3"

services:
  budibase:
    restart: unless-stopped
    image: budibase/budibase:latest
    container_name: ${CONTAINER_NAME}
    ports:
      - "${APP_PORT_HTTP}:80"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ACCESS_KEY: ${MINIO_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET}
      REDIS_PASSWORD: ${REDIS_PASS}
      COUCHDB_USER: ${DB_USER}
      COUCHDB_PASSWORD: ${DB_PASS}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
    networks:
      - 1panel-network
    volumes:
      - ${DATA_PATH}:/data
      - ${DB_PATH}:/opt/couchdb/data
    labels:  
      createdBy: "Apps"

networks:
  1panel-network:
    external: true