services:
  showdoc:
    image: registry.cn-shenzhen.aliyuncs.com/star7th/showdoc:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    tty: true
    volumes:
      - ./showdocdata/html:/var/www/html
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true